image: golang:1.24

stages:
  - lint
  - security
  - build

variables:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org,direct"

cache:
  paths:
    - .cache/go-mod/

before_script:
  - apt-get update && apt-get install -y unzip curl
  - cd pvz-cli
  - export GOMODCACHE="$CI_PROJECT_DIR/.cache/go-mod"
  - go mod download
  - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
  - go install github.com/securego/gosec/v2/cmd/gosec@v2.22.4

lint:
  stage: lint
  allow_failure: false
  only:
    - merge_requests
    - master
  script:
    - make lint
  artifacts:
    when: on_failure
    expire_in: 1 hour
    reports:
      dotenv: .golangci-report.env

security:
  stage: security
  only:
    - merge_requests
    - master
  allow_failure: false
  script:
    - make security

build:
  stage: build
  needs: [lint, security]
  only:
    - merge_requests
    - master
  script:
    - make build
  artifacts:
    paths:
      - pvz-cli/pvz
    expire_in: 1 day