image: golang:1.24

stages:
  - lint
  - security
  - build
  - test

variables:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org,direct"

cache:
  paths:
    - .cache/go-mod/

before_script:
  - apt-get update && apt-get install -y unzip curl
  - cd pvz
  - export GOMODCACHE="$CI_PROJECT_DIR/.cache/go-mod"
  - go mod download
  - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
  - go install github.com/securego/gosec/v2/cmd/gosec@v2.22.4

lint:
  stage: lint
  allow_failure: false
  only:
    - merge_requests
    - master
  script:
    - make lint
  artifacts:
    when: on_failure
    expire_in: 1 hour
    reports:
      dotenv: .golangci-report.env

security:
  stage: security
  only:
    - merge_requests
    - master
  allow_failure: false
  script:
    - make security

build:
  stage: build
  needs: [lint, security]
  only:
    - merge_requests
    - master
  script:
    - make build
  artifacts:
    paths:
      - pvz/pvz
    expire_in: 1 day

migrate-test:
  stage: test
  image: docker:24.0.7-cli
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache make curl unzip
    - cd pvz
    - |
      if [ -z "$ENV_FILE" ]; then
        echo "ERROR: ENV_FILE variable is not set"
        exit 1
      fi
    - echo "$ENV_FILE" > .env
    - export $(grep -v '^#' .env | xargs)
  script:
    - docker compose up -d postgres
    - |
      timeout=30
      while [ $timeout -gt 0 ]; do
        if docker compose exec -T postgres pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"; then
          echo "Postgres is ready!"
          break
        fi
        echo "Waiting for Postgres… ($timeout seconds left)"
        sleep 1
        timeout=$((timeout - 1))
      done
      if [ $timeout -eq 0 ]; then
        echo "ERROR: Postgres was not ready in time."
        exit 1
      fi
    - make tools/install
    - make migrate-up
    - make migrate-status
  after_script:
    - docker compose down